/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  IRouterErrors,
  IRouterErrorsInterface,
} from "../../../contracts/Maverick.sol/IRouterErrors";

const _abi = [
  {
    inputs: [],
    name: "RouterNotFactoryPool",
    type: "error",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "amountOutMinimum",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "amountOut",
        type: "uint256",
      },
    ],
    name: "RouterTooLittleReceived",
    type: "error",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "amountInMaximum",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "amountIn",
        type: "uint256",
      },
    ],
    name: "RouterTooMuchRequested",
    type: "error",
  },
  {
    inputs: [],
    name: "RouterZeroSwap",
    type: "error",
  },
] as const;

export class IRouterErrors__factory {
  static readonly abi = _abi;
  static createInterface(): IRouterErrorsInterface {
    return new utils.Interface(_abi) as IRouterErrorsInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IRouterErrors {
    return new Contract(address, _abi, signerOrProvider) as IRouterErrors;
  }
}
