/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  IRETH,
  IRETHInterface,
} from "../../../contracts/IRETHRouter.sol/IRETH";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint256",
        name: "_rethAmount",
        type: "uint256",
      },
    ],
    name: "getEthValue",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "_ethAmount",
        type: "uint256",
      },
    ],
    name: "getRethValue",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class IRETH__factory {
  static readonly abi = _abi;
  static createInterface(): IRETHInterface {
    return new utils.Interface(_abi) as IRETHInterface;
  }
  static connect(address: string, signerOrProvider: Signer | Provider): IRETH {
    return new Contract(address, _abi, signerOrProvider) as IRETH;
  }
}
