"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.callback = void 0;
const tslib_1 = require("tslib");
/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
exports.callback = tslib_1.__importStar(require("./callback"));
//# sourceMappingURL=index.js.map