/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  WrapperCompV3,
  WrapperCompV3Interface,
} from "../../contracts/WrapperCompV3";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
    ],
    name: "deposit",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "exchangeRate",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "dst",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
    ],
    name: "withdrawTo",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class WrapperCompV3__factory {
  static readonly abi = _abi;
  static createInterface(): WrapperCompV3Interface {
    return new utils.Interface(_abi) as WrapperCompV3Interface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): WrapperCompV3 {
    return new Contract(address, _abi, signerOrProvider) as WrapperCompV3;
  }
}
