/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import { Contract, utils } from "ethers";
const _abi = [
    {
        inputs: [
            {
                internalType: "uint256[2]",
                name: "amounts",
                type: "uint256[2]",
            },
            {
                internalType: "uint256",
                name: "minOut",
                type: "uint256",
            },
            {
                internalType: "bool",
                name: "useEth",
                type: "bool",
            },
        ],
        name: "add_liquidity",
        outputs: [
            {
                internalType: "uint256",
                name: "",
                type: "uint256",
            },
        ],
        stateMutability: "nonpayable",
        type: "function",
    },
];
export class ICurveCryptoFactory__factory {
    static abi = _abi;
    static createInterface() {
        return new utils.Interface(_abi);
    }
    static connect(address, signerOrProvider) {
        return new Contract(address, _abi, signerOrProvider);
    }
}
//# sourceMappingURL=ICurveCryptoFactory__factory.js.map