"use strict";
/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
Object.defineProperty(exports, "__esModule", { value: true });
exports.IRETHRouter__factory = void 0;
const ethers_1 = require("ethers");
const _abi = [
    {
        inputs: [
            {
                internalType: "uint256",
                name: "_amount",
                type: "uint256",
            },
            {
                internalType: "uint256",
                name: "_steps",
                type: "uint256",
            },
        ],
        name: "optimiseSwapFrom",
        outputs: [
            {
                internalType: "uint256[2]",
                name: "portions",
                type: "uint256[2]",
            },
            {
                internalType: "uint256",
                name: "amountOut",
                type: "uint256",
            },
        ],
        stateMutability: "nonpayable",
        type: "function",
    },
    {
        inputs: [
            {
                internalType: "uint256",
                name: "_amount",
                type: "uint256",
            },
            {
                internalType: "uint256",
                name: "_steps",
                type: "uint256",
            },
        ],
        name: "optimiseSwapTo",
        outputs: [
            {
                internalType: "uint256[2]",
                name: "portions",
                type: "uint256[2]",
            },
            {
                internalType: "uint256",
                name: "amountOut",
                type: "uint256",
            },
        ],
        stateMutability: "nonpayable",
        type: "function",
    },
    {
        inputs: [
            {
                internalType: "uint256",
                name: "_uniswapPortion",
                type: "uint256",
            },
            {
                internalType: "uint256",
                name: "_balancerPortion",
                type: "uint256",
            },
            {
                internalType: "uint256",
                name: "_minTokensOut",
                type: "uint256",
            },
            {
                internalType: "uint256",
                name: "_idealTokensOut",
                type: "uint256",
            },
            {
                internalType: "uint256",
                name: "_tokensIn",
                type: "uint256",
            },
        ],
        name: "swapFrom",
        outputs: [],
        stateMutability: "nonpayable",
        type: "function",
    },
    {
        inputs: [
            {
                internalType: "uint256",
                name: "_uniswapPortion",
                type: "uint256",
            },
            {
                internalType: "uint256",
                name: "_balancerPortion",
                type: "uint256",
            },
            {
                internalType: "uint256",
                name: "_minTokensOut",
                type: "uint256",
            },
            {
                internalType: "uint256",
                name: "_idealTokensOut",
                type: "uint256",
            },
        ],
        name: "swapTo",
        outputs: [],
        stateMutability: "payable",
        type: "function",
    },
];
class IRETHRouter__factory {
    static abi = _abi;
    static createInterface() {
        return new ethers_1.utils.Interface(_abi);
    }
    static connect(address, signerOrProvider) {
        return new ethers_1.Contract(address, _abi, signerOrProvider);
    }
}
exports.IRETHRouter__factory = IRETHRouter__factory;
//# sourceMappingURL=IRETHRouter__factory.js.map