/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from 'ethers'
import type { FunctionFragment, Result } from '@ethersproject/abi'
import type { Listener, Provider } from '@ethersproject/providers'
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from '../../common'

export interface DeployFolioHelperInterface extends utils.Interface {
  functions: {
    'deployFolio(address,address,bool,bytes)': FunctionFragment
  }

  getFunction(nameOrSignatureOrTopic: 'deployFolio'): FunctionFragment

  encodeFunctionData(
    functionFragment: 'deployFolio',
    values: [
      PromiseOrValue<string>,
      PromiseOrValue<string>,
      PromiseOrValue<boolean>,
      PromiseOrValue<BytesLike>
    ]
  ): string

  decodeFunctionResult(functionFragment: 'deployFolio', data: BytesLike): Result

  events: {}
}

export interface DeployFolioHelper extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this
  attach(addressOrName: string): this
  deployed(): Promise<this>

  interface: DeployFolioHelperInterface

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>
  listeners(eventName?: string): Array<Listener>
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this
  removeAllListeners(eventName?: string): this
  off: OnEvent<this>
  on: OnEvent<this>
  once: OnEvent<this>
  removeListener: OnEvent<this>

  functions: {
    deployFolio(
      deployer: PromiseOrValue<string>,
      expectedTokenAddress: PromiseOrValue<string>,
      isGoverned: PromiseOrValue<boolean>,
      encodedFolioDeployerCall: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>
  }

  deployFolio(
    deployer: PromiseOrValue<string>,
    expectedTokenAddress: PromiseOrValue<string>,
    isGoverned: PromiseOrValue<boolean>,
    encodedFolioDeployerCall: PromiseOrValue<BytesLike>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>

  callStatic: {
    deployFolio(
      deployer: PromiseOrValue<string>,
      expectedTokenAddress: PromiseOrValue<string>,
      isGoverned: PromiseOrValue<boolean>,
      encodedFolioDeployerCall: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<BigNumber>
  }

  filters: {}

  estimateGas: {
    deployFolio(
      deployer: PromiseOrValue<string>,
      expectedTokenAddress: PromiseOrValue<string>,
      isGoverned: PromiseOrValue<boolean>,
      encodedFolioDeployerCall: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>
  }

  populateTransaction: {
    deployFolio(
      deployer: PromiseOrValue<string>,
      expectedTokenAddress: PromiseOrValue<string>,
      isGoverned: PromiseOrValue<boolean>,
      encodedFolioDeployerCall: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>
  }
}
