/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { IFacade__factory } from "./IFacade__factory";
export { IReadFacet__factory } from "./IReadFacet__factory";
//# sourceMappingURL=index.js.map