/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  PreventTampering,
  PreventTamperingInterface,
} from "../../../contracts/PreventTampering.sol/PreventTampering";

const _abi = [
  {
    inputs: [],
    name: "deployCodehash",
    outputs: [
      {
        internalType: "bytes32",
        name: "",
        type: "bytes32",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class PreventTampering__factory {
  static readonly abi = _abi;
  static createInterface(): PreventTamperingInterface {
    return new utils.Interface(_abi) as PreventTamperingInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): PreventTampering {
    return new Contract(address, _abi, signerOrProvider) as PreventTampering;
  }
}
