"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.IERC20__factory = exports.extensions = void 0;
const tslib_1 = require("tslib");
/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
exports.extensions = tslib_1.__importStar(require("./extensions"));
var IERC20__factory_1 = require("./IERC20__factory");
Object.defineProperty(exports, "IERC20__factory", { enumerable: true, get: function () { return IERC20__factory_1.IERC20__factory; } });
//# sourceMappingURL=index.js.map