/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { SelfDestruct } from "./SelfDestruct";
export type { TestPreventTampering } from "./TestPreventTampering";
