"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.IStaticAV3TokenLM__factory = void 0;
/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
var IStaticAV3TokenLM__factory_1 = require("./IStaticAV3TokenLM__factory");
Object.defineProperty(exports, "IStaticAV3TokenLM__factory", { enumerable: true, get: function () { return IStaticAV3TokenLM__factory_1.IStaticAV3TokenLM__factory; } });
//# sourceMappingURL=index.js.map