/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  IConcentratorVault,
  IConcentratorVaultInterface,
} from "../../../contracts/VirtualERC20.sol/IConcentratorVault";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint256",
        name: "_pid",
        type: "uint256",
      },
      {
        internalType: "address",
        name: "_account",
        type: "address",
      },
    ],
    name: "getUserShare",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class IConcentratorVault__factory {
  static readonly abi = _abi;
  static createInterface(): IConcentratorVaultInterface {
    return new utils.Interface(_abi) as IConcentratorVaultInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IConcentratorVault {
    return new Contract(address, _abi, signerOrProvider) as IConcentratorVault;
  }
}
