/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { IConcentratorVault__factory } from "./IConcentratorVault__factory";
export { VirtualERC20__factory } from "./VirtualERC20__factory";
