/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import { Contract, utils } from "ethers";
const _abi = [
    {
        inputs: [
            {
                internalType: "contract IERC20",
                name: "tokenIn",
                type: "address",
            },
            {
                internalType: "uint256",
                name: "amountIn",
                type: "uint256",
            },
            {
                internalType: "bytes32[]",
                name: "commands",
                type: "bytes32[]",
            },
            {
                internalType: "bytes[]",
                name: "state",
                type: "bytes[]",
            },
        ],
        name: "routeSingle",
        outputs: [
            {
                internalType: "bytes[]",
                name: "returnData",
                type: "bytes[]",
            },
        ],
        stateMutability: "payable",
        type: "function",
    },
    {
        inputs: [
            {
                internalType: "contract IERC20",
                name: "tokenIn",
                type: "address",
            },
            {
                internalType: "contract IERC20",
                name: "tokenOut",
                type: "address",
            },
            {
                internalType: "uint256",
                name: "amountIn",
                type: "uint256",
            },
            {
                internalType: "uint256",
                name: "minAmountOut",
                type: "uint256",
            },
            {
                internalType: "address",
                name: "receiver",
                type: "address",
            },
            {
                internalType: "bytes32[]",
                name: "commands",
                type: "bytes32[]",
            },
            {
                internalType: "bytes[]",
                name: "state",
                type: "bytes[]",
            },
        ],
        name: "safeRouteSingle",
        outputs: [
            {
                internalType: "bytes[]",
                name: "returnData",
                type: "bytes[]",
            },
        ],
        stateMutability: "payable",
        type: "function",
    },
];
export class EnsoRouter__factory {
    static abi = _abi;
    static createInterface() {
        return new utils.Interface(_abi);
    }
    static connect(address, signerOrProvider) {
        return new Contract(address, _abi, signerOrProvider);
    }
}
//# sourceMappingURL=EnsoRouter__factory.js.map