/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import { Contract, utils } from "ethers";
const _abi = [
    {
        inputs: [],
        name: "refresh",
        outputs: [],
        stateMutability: "nonpayable",
        type: "function",
    },
];
class IAssetRegistry__factory {
    static abi = _abi;
    static createInterface() {
        return new utils.Interface(_abi);
    }
    static connect(address, signerOrProvider) {
        return new Contract(address, _abi, signerOrProvider);
    }
}
export { IAssetRegistry__factory };
//# sourceMappingURL=IAssetRegistry__factory.js.map