/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import { Contract, utils } from "ethers";
const _abi = [
    {
        inputs: [],
        name: "nonce",
        outputs: [
            {
                internalType: "uint48",
                name: "",
                type: "uint48",
            },
        ],
        stateMutability: "view",
        type: "function",
    },
    {
        inputs: [
            {
                internalType: "uint192",
                name: "amount",
                type: "uint192",
            },
            {
                internalType: "enum RoundingMode",
                name: "rounding",
                type: "uint8",
            },
        ],
        name: "quote",
        outputs: [
            {
                internalType: "address[]",
                name: "erc20s",
                type: "address[]",
            },
            {
                internalType: "uint256[]",
                name: "quantities",
                type: "uint256[]",
            },
        ],
        stateMutability: "view",
        type: "function",
    },
];
class IBasketHandler__factory {
    static abi = _abi;
    static createInterface() {
        return new utils.Interface(_abi);
    }
    static connect(address, signerOrProvider) {
        return new Contract(address, _abi, signerOrProvider);
    }
}
export { IBasketHandler__factory };
//# sourceMappingURL=IBasketHandler__factory.js.map