/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  IGaugeStakeDAO,
  IGaugeStakeDAOInterface,
} from "../../../contracts/StakeDAO.sol/IGaugeStakeDAO";

const _abi = [
  {
    inputs: [],
    name: "vault",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class IGaugeStakeDAO__factory {
  static readonly abi = _abi;
  static createInterface(): IGaugeStakeDAOInterface {
    return new utils.Interface(_abi) as IGaugeStakeDAOInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IGaugeStakeDAO {
    return new Contract(address, _abi, signerOrProvider) as IGaugeStakeDAO;
  }
}
