/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  IVaultStakeDAO,
  IVaultStakeDAOInterface,
} from "../../../contracts/StakeDAO.sol/IVaultStakeDAO";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "_recipient",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "_amount",
        type: "uint256",
      },
      {
        internalType: "bool",
        name: "_earn",
        type: "bool",
      },
    ],
    name: "deposit",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "_shares",
        type: "uint256",
      },
    ],
    name: "withdraw",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IVaultStakeDAO__factory {
  static readonly abi = _abi;
  static createInterface(): IVaultStakeDAOInterface {
    return new utils.Interface(_abi) as IVaultStakeDAOInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IVaultStakeDAO {
    return new Contract(address, _abi, signerOrProvider) as IVaultStakeDAO;
  }
}
