"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.RToken__factory = exports.FacadeRead__factory = void 0;
/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
var FacadeRead__factory_1 = require("./FacadeRead__factory");
Object.defineProperty(exports, "FacadeRead__factory", { enumerable: true, get: function () { return FacadeRead__factory_1.FacadeRead__factory; } });
var RToken__factory_1 = require("./RToken__factory");
Object.defineProperty(exports, "RToken__factory", { enumerable: true, get: function () { return RToken__factory_1.RToken__factory; } });
//# sourceMappingURL=index.js.map