/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IGaugeStakeDAO } from "./IGaugeStakeDAO";
export type { IVaultStakeDAO } from "./IVaultStakeDAO";
