"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.token = void 0;
const tslib_1 = require("tslib");
/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
exports.token = tslib_1.__importStar(require("./token"));
//# sourceMappingURL=index.js.map