/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  IInitializableStaticATokenLM,
  IInitializableStaticATokenLMInterface,
} from "../../../contracts/AaveV3.sol/IInitializableStaticATokenLM";

const _abi = [
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "aToken",
        type: "address",
      },
      {
        indexed: false,
        internalType: "string",
        name: "staticATokenName",
        type: "string",
      },
      {
        indexed: false,
        internalType: "string",
        name: "staticATokenSymbol",
        type: "string",
      },
    ],
    name: "InitializedStaticATokenLM",
    type: "event",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "aToken",
        type: "address",
      },
      {
        internalType: "string",
        name: "staticATokenName",
        type: "string",
      },
      {
        internalType: "string",
        name: "staticATokenSymbol",
        type: "string",
      },
    ],
    name: "initialize",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IInitializableStaticATokenLM__factory {
  static readonly abi = _abi;
  static createInterface(): IInitializableStaticATokenLMInterface {
    return new utils.Interface(_abi) as IInitializableStaticATokenLMInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IInitializableStaticATokenLM {
    return new Contract(
      address,
      _abi,
      signerOrProvider
    ) as IInitializableStaticATokenLM;
  }
}
