/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  IBasketHandler,
  IBasketHandlerInterface,
} from "../../../../contracts/weiroll-helpers/RTokenMintHelper.sol/IBasketHandler";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "account",
        type: "address",
      },
    ],
    name: "basketsHeldBy",
    outputs: [
      {
        components: [
          {
            internalType: "uint192",
            name: "bottom",
            type: "uint192",
          },
          {
            internalType: "uint192",
            name: "top",
            type: "uint192",
          },
        ],
        internalType: "struct BasketRange",
        name: "",
        type: "tuple",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IBasketHandler__factory {
  static readonly abi = _abi;
  static createInterface(): IBasketHandlerInterface {
    return new utils.Interface(_abi) as IBasketHandlerInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IBasketHandler {
    return new Contract(address, _abi, signerOrProvider) as IBasketHandler;
  }
}
