/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  IChainLinkFeedRegistry,
  IChainLinkFeedRegistryInterface,
} from "../IChainLinkFeedRegistry";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "base",
        type: "address",
      },
      {
        internalType: "address",
        name: "quote",
        type: "address",
      },
    ],
    name: "latestAnswer",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IChainLinkFeedRegistry__factory {
  static readonly abi = _abi;
  static createInterface(): IChainLinkFeedRegistryInterface {
    return new utils.Interface(_abi) as IChainLinkFeedRegistryInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IChainLinkFeedRegistry {
    return new Contract(
      address,
      _abi,
      signerOrProvider
    ) as IChainLinkFeedRegistry;
  }
}
