"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.IStaticATokenLM__factory = void 0;
/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
var IStaticATokenLM__factory_1 = require("./IStaticATokenLM__factory");
Object.defineProperty(exports, "IStaticATokenLM__factory", { enumerable: true, get: function () { return IStaticATokenLM__factory_1.IStaticATokenLM__factory; } });
//# sourceMappingURL=index.js.map