/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { ICurveStableSwapNG__factory } from "./ICurveStableSwapNG__factory";
//# sourceMappingURL=index.js.map