"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.VM__factory = void 0;
/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
var VM__factory_1 = require("./VM__factory");
Object.defineProperty(exports, "VM__factory", { enumerable: true, get: function () { return VM__factory_1.VM__factory; } });
//# sourceMappingURL=index.js.map