"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.IBooster__factory = void 0;
/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
var IBooster__factory_1 = require("./IBooster__factory");
Object.defineProperty(exports, "IBooster__factory", { enumerable: true, get: function () { return IBooster__factory_1.IBooster__factory; } });
//# sourceMappingURL=index.js.map