"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.IPriceSourceReceiver__factory = exports.IFrxEthFraxOracle__factory = exports.AggregatorV3Interface__factory = void 0;
/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
var AggregatorV3Interface__factory_1 = require("./AggregatorV3Interface__factory");
Object.defineProperty(exports, "AggregatorV3Interface__factory", { enumerable: true, get: function () { return AggregatorV3Interface__factory_1.AggregatorV3Interface__factory; } });
var IFrxEthFraxOracle__factory_1 = require("./IFrxEthFraxOracle__factory");
Object.defineProperty(exports, "IFrxEthFraxOracle__factory", { enumerable: true, get: function () { return IFrxEthFraxOracle__factory_1.IFrxEthFraxOracle__factory; } });
var IPriceSourceReceiver__factory_1 = require("./IPriceSourceReceiver__factory");
Object.defineProperty(exports, "IPriceSourceReceiver__factory", { enumerable: true, get: function () { return IPriceSourceReceiver__factory_1.IPriceSourceReceiver__factory; } });
//# sourceMappingURL=index.js.map