"use strict";
/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
Object.defineProperty(exports, "__esModule", { value: true });
exports.IPriceSourceReceiver__factory = void 0;
const ethers_1 = require("ethers");
const _abi = [
    {
        inputs: [
            {
                internalType: "bool",
                name: "isBadData",
                type: "bool",
            },
            {
                internalType: "uint104",
                name: "priceLow",
                type: "uint104",
            },
            {
                internalType: "uint104",
                name: "priceHigh",
                type: "uint104",
            },
            {
                internalType: "uint40",
                name: "timestamp",
                type: "uint40",
            },
        ],
        name: "addRoundData",
        outputs: [],
        stateMutability: "nonpayable",
        type: "function",
    },
    {
        inputs: [],
        name: "getPrices",
        outputs: [
            {
                internalType: "bool",
                name: "isBadData",
                type: "bool",
            },
            {
                internalType: "uint256",
                name: "priceLow",
                type: "uint256",
            },
            {
                internalType: "uint256",
                name: "priceHigh",
                type: "uint256",
            },
        ],
        stateMutability: "view",
        type: "function",
    },
];
class IPriceSourceReceiver__factory {
    static abi = _abi;
    static createInterface() {
        return new ethers_1.utils.Interface(_abi);
    }
    static connect(address, signerOrProvider) {
        return new ethers_1.Contract(address, _abi, signerOrProvider);
    }
}
exports.IPriceSourceReceiver__factory = IPriceSourceReceiver__factory;
//# sourceMappingURL=IPriceSourceReceiver__factory.js.map