/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { CurveRouterCall } from "./CurveRouterCall";
export type { ICurveRouter } from "./ICurveRouter";
