/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import { Contract, utils } from "ethers";
const _abi = [
    {
        inputs: [],
        name: "forSwaps",
        outputs: [
            {
                components: [
                    {
                        internalType: "address",
                        name: "lp",
                        type: "address",
                    },
                    {
                        internalType: "bool",
                        name: "stable",
                        type: "bool",
                    },
                    {
                        internalType: "address",
                        name: "token0",
                        type: "address",
                    },
                    {
                        internalType: "address",
                        name: "token1",
                        type: "address",
                    },
                    {
                        internalType: "address",
                        name: "factory",
                        type: "address",
                    },
                    {
                        internalType: "uint256",
                        name: "pool_fee",
                        type: "uint256",
                    },
                ],
                internalType: "struct SwapLp[]",
                name: "",
                type: "tuple[]",
            },
        ],
        stateMutability: "view",
        type: "function",
    },
];
export class IGeneratedInterface__factory {
    static abi = _abi;
    static createInterface() {
        return new utils.Interface(_abi);
    }
    static connect(address, signerOrProvider) {
        return new Contract(address, _abi, signerOrProvider);
    }
}
//# sourceMappingURL=IGeneratedInterface__factory.js.map